version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # need the env file for some reason
    # env_file: .env
    ports:
      - "3000:3000"

    # need this line or react-app scripts will crash and exit with 0
    stdin_open: true
